const produtos = [
  {
    id: 1,
    nome: 'Camiseta Branca',
    marca: 'Hering',
    categoria: 'Masculino',
    valor: 29.9,
    descricao: 'Camiseta branca, gola careca sem estampa.',
    palavrasChave: 'camiseta basica',
    p: 10,
    m: 6,
    g: 11,
    unico: 0,
    imagens: [
      {
        id: 20,
        idProduto: 1,
        imagem: 'https://i.imgur.com/enyGWWB.jpg',
      },
    ],
    perguntas: [
      {
        id: 1,
        idProduto: 1,
        pergunta: 'Pergunta 1',
        resposta: 'Resposta 1',
      },
      {
        id: 2,
        idProduto: 1,
        pergunta: 'Pergunta 2',
        resposta: 'Resposta 2',
      },
    ],
    ativo: true,
  },
  {
    id: 2,
    nome: 'Cropped Jeans',
    marca: 'Handbook',
    categoria: 'Casacos',
    valor: 199.0,
    descricao:
      'Jaqueta confeccionada em tecido jeans estonada lavagem média.\nSua modelagem cropped, bolsos frontais , botões encapado, costura na linha cor ocre, barra desfiada.\nA única jaqueta que não pode faltar no armário, combina com tudo, para o look casual, o look descolado, look ofice.\nComposição: 100% Algodão',
    palavrasChave: 'Jaqueta Jeans Cropped',
    p: 10,
    m: 2,
    g: 5,
    unico: 0,
    imagens: [
      {
        id: 7,
        idProduto: 2,
        imagem: 'https://i.imgur.com/E6iioYu.jpg',
      },
      {
        id: 8,
        idProduto: 2,
        imagem: 'https://i.imgur.com/Zd3Fs4k.jpg',
      },
      {
        id: 9,
        idProduto: 2,
        imagem: 'https://i.imgur.com/Ry8ImvZ.jpg',
      },
    ],
    perguntas: [
      {
        id: 5,
        idProduto: 2,
        pergunta: 'É jeans?',
        resposta: 'Sim',
      },
      {
        id: 6,
        idProduto: 2,
        pergunta: 'É 100% algodão?',
        resposta: 'Sim',
      },
    ],
    ativo: true,
  },
  {
    id: 3,
    nome: 'Blusão cinza',
    marca: 'git',
    categoria: 'Casacos',
    valor: 50.0,
    descricao: 'Blusa que dá o atributo de estrutura de dados',
    palavrasChave: 'Blusa Moletom',
    p: 2,
    m: 4,
    g: 5,
    unico: 2,
    imagens: [
      {
        id: 23,
        idProduto: 3,
        imagem: 'https://i.imgur.com/UDW8Ydr.jpg',
      },
      {
        id: 24,
        idProduto: 3,
        imagem: 'https://i.imgur.com/HMg5fKY.jpg',
      },
    ],
    perguntas: [
      {
        id: 7,
        idProduto: 3,
        pergunta: 'azul?',
        resposta: 'nao',
      },
      {
        id: 8,
        idProduto: 3,
        pergunta: 'tem pra gordao?',
        resposta: 'tem',
      },
    ],
    ativo: true,
  },
  {
    id: 4,
    nome: 'Calça Jeans',
    marca: 'FATAL',
    categoria: 'Masculino',
    valor: 99.0,
    descricao: 'Calça Jeans Skinny',
    palavrasChave: 'Jeans Skinny',
    p: 10,
    m: 5,
    g: 5,
    unico: 0,
    imagens: [
      {
        id: 25,
        idProduto: 4,
        imagem: 'https://i.imgur.com/epsOlWq.jpg',
      },
      {
        id: 26,
        idProduto: 4,
        imagem: 'https://i.imgur.com/yoCiPVP.jpg',
      },
    ],
    perguntas: [
      {
        id: 14,
        idProduto: 4,
        pergunta: 'Se lavar encolhe?',
        resposta: 'Não',
      },
      {
        id: 15,
        idProduto: 4,
        pergunta: 'Tem possibilidade de troca?',
        resposta: 'Sim.',
      },
    ],
    ativo: true,
  },
  {
    id: 5,
    nome: 'Calça Sarja Preta',
    marca: 'FATAL',
    categoria: 'Masculino',
    valor: 89.0,
    descricao: 'Calça Sarja Preta',
    palavrasChave: 'Calça Sarja Preta',
    p: 10,
    m: 22,
    g: 50,
    unico: 0,
    imagens: [
      {
        id: 27,
        idProduto: 5,
        imagem: 'https://i.imgur.com/hgGNHOy.jpg',
      },
      {
        id: 28,
        idProduto: 5,
        imagem: 'https://i.imgur.com/Cfei9s6.jpg',
      },
    ],
    perguntas: [
      {
        id: 16,
        idProduto: 5,
        pergunta: 'O tecido desbota?',
        resposta: 'Depois de um tempo, é inevitável.',
      },
    ],
    ativo: true,
  },
  {
    id: 6,
    nome: 'Jaqueta Corta Vento',
    marca: 'AMBER',
    categoria: 'Casacos',
    valor: 150.0,
    descricao: 'Jaqueta Corta vento Rosa e preto com detalhes camuflados.',
    palavrasChave: 'Corta-vento preto rosa camuflado Amber',
    p: 5,
    m: 10,
    g: 15,
    unico: 0,
    imagens: [
      {
        id: 29,
        idProduto: 6,
        imagem: 'https://i.imgur.com/lSpwems.jpg',
      },
      {
        id: 30,
        idProduto: 6,
        imagem: 'https://i.imgur.com/ApZdp1s.jpg',
      },
      {
        id: 31,
        idProduto: 6,
        imagem: 'https://i.imgur.com/t950dtU.jpg',
      },
    ],
    perguntas: [
      {
        id: 17,
        idProduto: 6,
        pergunta: 'Tem garantia para troca?',
        resposta: 'Sim',
      },
    ],
    ativo: true,
  },
  {
    id: 7,
    nome: 'Jaqueta Vintage',
    marca: 'Handbook',
    categoria: 'Casacos',
    valor: 199.0,
    descricao:
      'Jaqueta confeccionada em confeccionada tecido com toque aveludado aspecto lavado.\nSua modelagem quadrada, com bolsos frontais quadrado e lapela e fechamento botão, abertura frontal com fechamento botões , barra larga com elástico embutido , manga longa com punho largo e elástico embutido.\nAquela jaqueta que salva o dia, perfeita para usar com uma pantalona ou mesmo com uma calça skynny, muito casual, para usar todos os dias.\nComposição: 95% Poliéster 5% Poliamida',
    palavrasChave: 'Jaqueta Vintage Poliester',
    p: 10,
    m: 8,
    g: 7,
    unico: 0,
    imagens: [
      {
        id: 32,
        idProduto: 7,
        imagem: 'https://i.imgur.com/d5d4Pdb.jpg',
      },
      {
        id: 33,
        idProduto: 7,
        imagem: 'https://i.imgur.com/DJdytw1.jpg',
      },
      {
        id: 34,
        idProduto: 7,
        imagem: 'https://i.imgur.com/1iJ8I7J.jpg',
      },
      {
        id: 35,
        idProduto: 7,
        imagem: 'https://i.imgur.com/zJody46.jpg',
      },
    ],
    perguntas: [
      {
        id: 18,
        idProduto: 7,
        pergunta: 'Desbota com facilidade?',
        resposta: 'Não',
      },
      {
        id: 19,
        idProduto: 7,
        pergunta: 'O tecido é leve?',
        resposta: 'Sim',
      },
    ],
    ativo: true,
  },
  {
    id: 8,
    nome: 'Tuguir 5050',
    marca: 'Tuguir',
    categoria: 'Acessórios',
    valor: 100.0,
    descricao: 'Relogio Analogico Cinza Tuguir 5050',
    palavrasChave: 'Tuguir Relogio Analogico Cinza',
    p: 0,
    m: 0,
    g: 0,
    unico: 5,
    imagens: [
      {
        id: 36,
        idProduto: 8,
        imagem: 'https://i.imgur.com/h7281Fz.jpg',
      },
      {
        id: 37,
        idProduto: 8,
        imagem: 'https://i.imgur.com/UOAhQZX.jpg',
      },
    ],
    perguntas: [
      {
        id: 20,
        idProduto: 8,
        pergunta: 'Tem resistência a agua?',
        resposta: 'Sim, 10m.',
      },
    ],
    ativo: true,
  },
  {
    id: 9,
    nome: 'Camiseta Caveira',
    marca: 'JOSS',
    categoria: 'Feminino',
    valor: 50.0,
    descricao: 'Camiseta Feminina Básica Joss com caimento reto estampa em silk, máxima qualidade e conforto para o seu dia a dia.',
    palavrasChave: 'Camiseta Caveira Preta',
    p: 3,
    m: 5,
    g: 10,
    unico: 0,
    imagens: [
      {
        id: 38,
        idProduto: 9,
        imagem: 'https://i.imgur.com/5LRpoig.jpg',
      },
      {
        id: 39,
        idProduto: 9,
        imagem: 'https://i.imgur.com/i3gq38Q.jpg',
      },
    ],
    perguntas: [
      {
        id: 21,
        idProduto: 9,
        pergunta: 'É de algodão?',
        resposta: 'Sim',
      },
    ],
    ativo: true,
  },
  {
    id: 10,
    nome: 'Boné Element',
    marca: 'ELEMENT',
    categoria: 'Acessórios',
    valor: 150.0,
    descricao: 'Boné preto e amarelo Element',
    palavrasChave: 'Boné Aberto Element Preto Amarelo',
    p: 0,
    m: 0,
    g: 0,
    unico: 5,
    imagens: [
      {
        id: 40,
        idProduto: 10,
        imagem: 'https://i.imgur.com/nU3Bd2O.jpg',
      },
      {
        id: 41,
        idProduto: 10,
        imagem: 'https://i.imgur.com/oYYsRui.jpg',
      },
      {
        id: 42,
        idProduto: 10,
        imagem: 'https://i.imgur.com/Mc95eU8.jpg',
      },
    ],
    perguntas: [
      {
        id: 22,
        idProduto: 10,
        pergunta: 'Há garantia para trocas?',
        resposta: 'Sim. Apenas para defeitos de fábrica.',
      },
    ],
    ativo: true,
  },
  {
    id: 11,
    nome: 'Blusa Hora da Diva',
    marca: 'Hora da Diva',
    categoria: 'Feminino',
    valor: 60.0,
    descricao:
      'Blusa de Diva confeccionada em musseline com lycra na cor branca. Tecido leve, com suave transparência e toque macio. Super elegante e charmosa possui ombros drapeados, mangas bufantes e punhos bem românticos com lastex. Golinha alta também com lastex. Composição 95% poliéster, 5% lycra. PP veste manequim 34 . P veste manequim 36-38. M veste manequim 38-40 G veste manequim 42-44. GG veste manequim 46-48.',
    palavrasChave: 'Branca Gola-alta',
    p: 4,
    m: 4,
    g: 2,
    unico: 0,
    imagens: [
      {
        id: 43,
        idProduto: 11,
        imagem: 'https://i.imgur.com/kuTVydr.jpg',
      },
      {
        id: 44,
        idProduto: 11,
        imagem: 'https://i.imgur.com/IxkiVWl.jpg',
      },
      {
        id: 45,
        idProduto: 11,
        imagem: 'https://i.imgur.com/ATMvRGG.jpg',
      },
    ],
    perguntas: [
      {
        id: 23,
        idProduto: 11,
        pergunta: 'Há a possibilidade de troca?',
        resposta: 'Sim',
      },
    ],
    ativo: true,
  },
  {
    id: 12,
    nome: 'Jaqueta Bomber',
    marca: 'Handbook',
    categoria: 'Casacos',
    valor: 299.0,
    descricao:
      'Jaqueta confeccionada em tecido de cetim.\nSua modelagem bomber curtinha,gola padre, manga longa de punho de elástico, bolso faca lateral, fechamento zíper metal frontal, elástico embutido traseiro.\nAquela jaqueta que todos nos precisamos ter, perfeita para usar com vestido ou calça jeans, para uma balada um dia no escritório , um passeio no shopping , ou seja ela te acompanha para todos os lugares.',
    palavrasChave: 'Jaqueta Bomber Cetim',
    p: 12,
    m: 12,
    g: 10,
    unico: 0,
    imagens: [
      {
        id: 58,
        idProduto: 12,
        imagem: 'https://i.imgur.com/5vKrKr8.jpg',
      },
      {
        id: 59,
        idProduto: 12,
        imagem: 'https://i.imgur.com/p5hfgUG.jpg',
      },
      {
        id: 60,
        idProduto: 12,
        imagem: 'https://i.imgur.com/gBJNpTl.jpg',
      },
    ],
    perguntas: [
      {
        id: 25,
        idProduto: 12,
        pergunta: 'É Cetim?',
        resposta: 'sim',
      },
      {
        id: 26,
        idProduto: 12,
        pergunta: 'É impermeável?',
        resposta: 'Sim',
      },
    ],
    ativo: true,
  },
];
